import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ChakraProviders } from '../providers/chakraProvider'
import { MetamaskProvider } from "../hooks/useMetamask";
import MetamaskLayout from './metamaskLayout';
import { ReduxProvider } from '@/providers/reduxProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ProChain',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MetamaskProvider>
          <ChakraProviders>
              <ReduxProvider>
                <MetamaskLayout>
                    {children}
                </MetamaskLayout>
              </ReduxProvider>
          </ChakraProviders>
        </MetamaskProvider>
        </body>
    </html>
  )
}
